alisite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('view_recipe/<str:rec_pk>', views.view_recipe, name='view_recipe'),
    path('edit_recipe/<str:rec_pk>', views.edit_recipe, name='edit_recipe'),
    path('delete_recipe/<str:rec_pk>', views.delete_recipe, name='delete_recipe'),
    path('get_recipe', views.get_recipe, name='get_recipe'),
    path('register', views.register, name='register'),
    path('logout', views.logout_request, name='logout'),
    path('login', views.login_request, name='login'),
    path('search', views.search, name='search'),
]

recipes/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User




class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    image = models.URLField(blank=True, null=True,)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    ingredients = models.CharField(max_length=2000, blank=True, null=True)
    servings = models.IntegerField(blank=True, null=True)
    site = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title

recipes/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from .models import Recipe, Category


class RecipeForm(forms.ModelForm):

    # custom form fields
    ingredients = forms.CharField(widget=CKEditorWidget(config_name='ingredients'), required=False)
    new_category = forms.CharField(required=False, label="New Category", widget=forms.TextInput(
        attrs={'placeholder': 'title'}))
    cat_image = forms.URLField(required=False, label="Image", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    cat_description = forms.CharField(required=False, label="Description", widget=forms.Textarea(
        attrs={'rows': '4', 'cols': '12', 'placeholder': 'Short description of category'}))
    category = forms.ModelChoiceField(required=False, queryset=Category.objects.all())

    # ModelForm fields               
    class Meta:
        model = Recipe
        fields = ['title', 'body', 'servings']
        widgets = {
            'body': CKEditorWidget(),
        }

    # relating available categories in drop-down to specific user
    def __init__(self, *args, user=None ,**kwargs):
        super().__init__(*args, **kwargs)
        if user:
            category = self.fields['category']
            category.queryset = Category.objects.filter(user__pk=user.pk)    

    # custom form validation
    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')
        title = cleaned_data.get('title')
        if not category and not new_category:
            raise forms.ValidationError(
                "No category given")
        if not title:
            raise forms.ValidationError(
                "No title given")


class ScraperForm(forms.Form):

    # custom form fields
    url = forms.URLField(label="Recipe URL", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    new_category = forms.CharField(required=False, label="New Category", widget=forms.TextInput(
        attrs={'placeholder': 'title'}))
    cat_image = forms.URLField(required=False, label="Image", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    cat_description = forms.CharField(required=False, label="Description", widget=forms.Textarea(
        attrs={'rows': '4', 'cols': '12', 'placeholder': 'Short description of new category'}))        
    category = forms.ModelChoiceField(required=False, queryset=Category.objects.all())

    # relating available categories in drop-down to specific user
    def __init__(self, *args, user=None ,**kwargs):
        super().__init__(*args, **kwargs)
        if user:
            category = self.fields['category']
            category.queryset = Category.objects.filter(user__pk=user.pk)

    # custom form validation
    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')
        if not category and not new_category:
            raise forms.ValidationError(
                "No category")        

recipes/views.py
import os

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate

from recipe_scrapers import scrape_me

from .forms import RecipeForm, ScraperForm
from .models import Recipe, Category
from .utils import *


# homepage
# all recipes and categories belonging to the user are queried and 
# sent to the front end to be rendered
def index(request):
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)
    django_settings = os.environ.get('DJANGO_SETTINGS_MODULE')
    if django_settings == 'alisite.settings.development':
        development = True
    else:
        development = False
            
    # some cleanup to find empty categories and delete them
    if categories:
        for cat in categories:
            empty_cat = True
            for rec in recipes:
                if rec.category.pk == cat.pk:
                    empty_cat = False
            if empty_cat:
                cat_del = Category.objects.get(pk=cat.pk)
                cat_del.delete()

            # update list of categories to reflect deleted ones    
            categories = Category.objects.filter(user__pk=user_pk)    

    return render(request, 'recipes/index.html', {
        'categories': categories,
        'recipes': recipes,
        'development': development
    })

# creating new recipe
def create(request):
    user_pk = request.user.pk  
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)   

    # handle for RecipeForm submission        
    if request.method == 'POST':      
        form = RecipeForm(request.POST)           
        if form.is_valid():

            # check if new category was given
            new_category = request.POST.get('new_category')            
            if new_category:
                # check if new category alredy exists
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')

                    data = collect_data(request)
                    rec_form = RecipeForm(user=request.user, initial=data)

                    return render(request, 'recipes/create.html', {
                        'rec_form': rec_form,
                        'categories': categories,
                        'recipes': recipes,
                    })

                # create recipe with new category       
                recipe = create_recipe_new_cat(user_pk, request)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            
            # create recipe with existing category
            elif request.POST.get('category'):
                recipe = create_recipe_existing_cat(user_pk, request)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))    

        # error message for incomplete recipe
        else:
            messages.info(request, 'Note: You must provide a title, category and body to save the recipe')         
                
            data = collect_data(request)               
            rec_form = RecipeForm(user=request.user, initial=data)

            return render(request, 'recipes/create.html', {
            'rec_form': rec_form,
            'categories': categories,
            'recipes': recipes,
        })


    rec_form = RecipeForm(user=request.user, initial={'servings': 1}) 
    
    return render(request, 'recipes/create.html', {
        'rec_form': rec_form,
        'categories': categories,
        'recipes': recipes,
    })

# editing a recipe
def edit_recipe(request, rec_pk):
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)

    # handle for RecipeForm submission
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():   
            recipe = Recipe.objects.get(pk=rec_pk)

            # check if new category was given
            new_category = request.POST.get('new_category')            
            if new_category:

                # check if new category alredy exists
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')

                    data = {'category': request.POST.get('category'),
                    'title': request.POST.get('title'),
                    'body': request.POST.get('body'),
                    'servings': request.POST.get('servings'),
                    'ingredients': request.POST.get('ingredients') }
                    rec_form = RecipeForm(user=request.user, initial=data)

                    return render(request, 'recipes/edit.html', {
                        'rec_form': rec_form,
                        'categories': categories,
                        'recipes': recipes,
                        'recipe': recipe
                    })

                # edit recipe with new category       
                recipe = edit_recipe_new_cat(request, recipe)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            
            # edit recipe with existing category
            elif request.POST.get('category'):
                recipe = edit_recipe_existing_cat(request, recipe)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))    

        # error message for incomplete form
        else:
            messages.info(request, 'Note: You must give a title, category and body to save the recipe') 

            data = collect_data(request)
            rec_form = RecipeForm(user=request.user, initial=data)

            return render(request, 'recipes/edit.html', {
            'rec_form': rec_form,
            'recipe': recipe,
            'categories': categories,
            'recipes': recipes,
        })   

    # retrieve recipe to be edited
    recipe = Recipe.objects.get(pk=rec_pk)

    # gather data to populate form to be edited   
    data = {'title': recipe.title,
            'category': recipe.category,
            'servings': recipe.servings,
            'body': recipe.body,
            'ingredients': recipe.ingredients} 
    rec_form = RecipeForm(initial=data, user=request.user)        
            
    return render(request, 'recipes/edit.html', {
        'categories': categories,
        'recipes': recipes,
        'rec_form': rec_form,
        'recipe': recipe,
    })

# lets scrape some recipes!
def get_recipe(request):

    # set up forms etc.
    form = ScraperForm(user=request.user)
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)

    # handle for form submission
    if request.method == 'POST':
        form = ScraperForm(request.POST)
        if form.is_valid():
            try:                                                       
                
                # check if new category alredy exists
                new_category = request.POST.get('new_category')
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')
                    return redirect(reverse('recipes:get_recipe', kwargs={'user_pk': user_pk}))
                
                # handle for new category
                if new_category:                
                    recipe_url = request.POST.get('url')
                    online_recipe = scrape_me(recipe_url, wild_mode = True)                     
                    recipe = scrape_recipe_new_cat(user_pk, request, online_recipe)
                    recipe.save()                   
                    return  redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))

                # handle for existing category 
                else:                    
                    recipe_url = request.POST.get('url')
                    online_recipe = scrape_me(recipe_url, wild_mode = True)                      
                    recipe = scrape_recipe(user_pk, request, online_recipe)   
                    recipe.save()                    
                    return  redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            except:
                messages.error(request, 'Oops, something went wrong. Please check that you have given a category. It is also possible that this recipe simply cannot be scraped :(')               
                data = {'url': request.POST.get('url'),
                        'category': request.POST.get('category'),
                        'new_category': request.POST.get('new_category'),
                        'cat_image': request.POST.get('cat_image'),
                        'cat_description': request.POST.get('cat_description')}                
                form = ScraperForm(initial=data, user=request.user)
                                
                return render(request, 'recipes/get_recipe.html', {
                    'form': form,
                    'recipes': recipes,
                    'categories': categories
                })                        
        else:
            messages.error(request, 'Please provide a category')           
            data = {'url': request.POST.get('url'),

recipes/templates/recipes/create.html
{% extends 'recipes/header.html' %}
{% block content %}
    <h1 class='josefont'>New Recipe</h1>
    <br /><br />

    <form action="{% url 'recipes:create' %}" method="POST">
        {% csrf_token %}
        {% include "recipes/includes/recipe_form_create.html" %}            
    </form>
{% endblock %}

recipes/templates/recipes/edit.html
{% extends 'recipes/header.html' %} 
{% block content %}
    <h3 class='josefont'>Edit</h3>
    <h5 class='josefont' style="font-size: 2em;">{{recipe.title}}</h5>
    <br> <br>
    
    <form action="{% url 'recipes:edit_recipe' rec_pk=recipe.pk %}"method="POST">
      {% csrf_token %}
      {% include "recipes/includes/recipe_form_edit.html" %}
    </form>
{% endblock %}

recipes/templates/recipes/get_recipe.html
{% extends 'recipes/header.html' %}

{% block content %}
    <div>
        <h1 class="josefont">From The Internet</h1>
        <hr>
        <br>
        <h6 class="josefont" style="font-size: 1.75rem" >Paste the URL for the recipe you wish to save</h6>
        <h6 class="josefont" style="font-size: 1.75rem">and choose a category</h6>
    </div>
    <br><br>
    <form action="{% url 'recipes:get_recipe' %}" method="post">
        {% csrf_token %}
        <div class="center">
            <div class="column-container" style="border: 1px solid #ccc; border-radius: 10px; padding: 25px; background-color: #383e3e; width: 300px">
                <div class="column-container" style="align-items: center;">
                    <div class="cat-flex" >
                        {{ form.url.label }}
                        {{ form.url }}
                    </div>
                    <div class="cat-flex" >
                        {{ form.category.label }}
                        {{ form.category }}
                    </div>
                </div>
                <br><br>
                <div style="border: 1px solid #ccc; border-radius: 10px; padding: 15px; background-color: #2c3434">
                    <div class="cat-flex">
                        {{ form.new_category.label }}
                        {{ form.new_category }}
                    </div>
                    <div class="cat-flex">
                        {{ form.cat_image.label }}
                        {{ form.cat_image }}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                    <div class="cat-flex">
                        {{ form.cat_description.label }}
                        {{ form.cat_description }}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                </div>
                <br><br>
                <div style="display: flex; justify-content: center;">
                    <input id="button" type="submit" value="go!">
                </div>               
            </div>            
        </div>
    </form>

{% endblock %}

recipes/templates/recipes/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--load static files-->
    {% load static %}

    <!--imports for bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" 
    integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" 
    crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" 
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" 
    crossorigin="anonymous"></script>  

    <!--custom css-->
    <link rel="stylesheet" href="{% static 'recipes/style.css' %}" />

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <title>Ali's Kitchen</title>
  </head>
  <body>

    <!--navbar-->
    {% include "recipes/includes/navbar.html" %}

    <!--messages-->
    {% include "recipes/includes/messages.html" %}
    <br><br>

    <!--body content-->
    <div class="container">
      {% block content %} 
      {% endblock %}
    </div>

    <div class="footer-div"></div>
  </body>
</html>

recipes/templates/recipes/index.html
{% extends 'recipes/header.html' %}
{% block content %}
    <div style="display: flex; justify-content: center;">
        {% if user.is_authenticated %}
            <div class="row" style="display: flex; justify-content: center;">
                {% if categories %}
                    {% for cat in categories %}        
                        <div class="card" style="text-align: center; width: 18rem; margin: 15px; background-color: #383e3e; border: 1px solid #a9aaaa; padding: 15px; color: whitesmoke">

                                <img class="card-img-top" src="{{ cat.image }}" alt="No Image" width='250' height='300'>

                            <div class="card-body">
                                <h5 class="card-title">{{ cat.name| title }}</h5>
                                <p class="card-text">{{cat.description}}</p>
                            </div>
                            <div class="dropdown" style="display: flex; justify-content: center;">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Recipes
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    {% for rec in recipes|dictsort:"title" %}
                                        {% if rec.category == cat %}
                                            <a class="dropdown-item" href="{% url 'recipes:view_recipe' rec_pk=rec.pk %}" >{{rec}}</a>
                                        {% endif %}
                                    {% endfor %}
                                
                                </div>
                            </div>          
                        </div>       
                    {% endfor %}    
                {% else %}
                    <h1 class="josefont" style="text-align: center;">No Recipes</h1>
                    <br><br>
                    <p class="josefont" style="font-size: 1.75rem;"><a href="/create">New</a></p>
                    <p class="josefont" style="font-size: 1.75rem;"><a href="/get_recipe">From The Internet</a></p>
                {% endif %}
        {% else %}
            <div style="text-align: center;">
                <h1 class="alwaysforever">Ali's Kitchen</h1>
                <br>
                {{request.content}}
                <p><a href="/login"><strong>Login</strong></a></p>
                {% if development %}
                    <p><small>or</small></p>
                    <p><a href="/register"><strong>Register</strong></a></p>
                    <p><small>a new account</small></p>
                {% endif %}                   
            </div>

        {% endif %}        
        </div>

    </div>

{% endblock %}

recipes/templates/recipes/login.html
{% extends 'recipes/header.html' %} 
{% block content %}
    <form method="POST" action="{% url 'recipes:login' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="column-container" style="width: 250px; margin-bottom: 10px">
                {{field.errors}}
                {{field.label}}
                {{field}}
            </div>
        {% endfor %}
        <br>
        <input type="submit" value="login" id="button">
    </form>
    <br>

{% endblock %}

recipes/templates/recipes/register.html
{% extends 'recipes/header.html' %} 
{% block content %}
    <form method="POST" action="{% url 'recipes:register' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="column-container" style="width: 250px; margin-bottom: 10px">
                {{field.errors}}
                {{field.label}}
                {{field}}
            </div>
        {% endfor %}
        <br>
        <input type="submit" value="submit" id="button">
    </form>
    <br>
    If you already have an account, log in <a href="{% url 'recipes:login' %}"><strong>here</strong></a>.
{% endblock %}

recipes/templates/recipes/scraper.html
{% extends 'recipes/header.html' %}

{% block content %}
    <div style="text-align: center;">
        <h3>Get Recipe From The Internet</h3>
        <hr>
        <br>
        <h6>Paste the URL for the recipe you wish to save</h6>
        <h6>and choose a category</h6>
    </div>
    <br><br>
    <form action="{% url 'recipes:recipe_scraper' user_pk=user.pk %}" method="post">
        {% csrf_token %}
        <div class="center">
            <div class="column-container" style="border: 1px solid #ccc; border-radius: 15px; padding: 33px; background-color: #383e3e">
                <div class="column-container" style="align-items: center;">
                    <div class="cat-flex" >
                        {{ form.url.label }}
                        {{ form.url }}
                    </div>
                    <div class="cat-flex" >
                        {{ form.category.label }}
                        {{ form.category }}
                    </div>
                </div>
                <br><br>
                <div style="border: 1px solid #ccc; border-radius:  15px; padding: 33px; background-color: #2c3434">
                    <div class="cat-flex">
                        {{ form.new_category.label }}
                        {{ form.new_category }}
                    </div>
                    <div class="cat-flex">
                        {{ form.cat_image.label }}
                        {{ form.cat_image }}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                    <div class="cat-flex">
                        {{ form.cat_description.label }}
                        {{ form.cat_description }}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                </div>
                <br><br>
                <div style="display: flex; justify-content: center;">
                    <input id="button" type="submit" value="go!">
                </div>

                
            </div>
            






            
        </div>

    </form>

{% endblock %}

recipes/templates/recipes/search.html
{% extends 'recipes/header.html' %} 
{% block content %}

    {% if search_title or search_ingredients %}
        <ul>
            {% for recipe in search_list %}
                <li>
                    <a href="{% url 'recipes:view_recipe' rec_pk=recipe.pk %}">
                        {{recipe.title}}
                    </a>    
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h5> No Results Found For "{{user_search}}"</h5>
    {% endif %}  

{% endblock %}

recipes/templates/recipes/view_recipe.html
{% extends 'recipes/header.html' %} 
{% block content %}
  <div>
    <div style="text-align: center;">
      {% if recipe.site %}
        <h6><small style="color: rgb(168, 167, 167)">{{ recipe.site }}</small></h6>
      {% endif %}
      <h3>{{ recipe.title.title }} </h3>
      {% if recipe.servings %}
        <h4><small style="color: rgb(168, 167, 167)">(serves {{ recipe.servings }})</small></h4>
      {% endif %}  
    </div>
      <hr>
      <div style="padding-right: 30px">
        <ul>
          {{ recipe.ingredients| safe }}
        </ul>
      </div>
      <hr>
    <br>
    <div class="center">
      <div class="recipe-text">
        {{ recipe.body| safe }}
      </div>
    </div>
  </div>
  <br><br>
  <div class="center">
    <div class="edit-button">
      <a href="{% url 'recipes:edit_recipe' rec_pk=recipe.pk %}">
        <button id="button">Edit</button>
      </a>
    </div>
  </div>

  <div class="footer-div"> </div>

{% endblock %}