alisite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('view_recipe/<str:rec_pk>', views.view_recipe, name='view_recipe'),
    path('edit_recipe/<str:rec_pk>', views.edit_recipe, name='edit_recipe'),
    path('delete_recipe/<str:rec_pk>', views.delete_recipe, name='delete_recipe'),
    path('get_recipe', views.get_recipe, name='get_recipe'),
    path('register', views.register, name='register'),
    path('logout', views.logout_request, name='logout'),
    path('login', views.login_request, name='login'),
    path('search', views.search, name='search'),
]

recipes/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User




class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    image = models.URLField(blank=True, null=True,)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    ingredients = models.CharField(max_length=2000, blank=True, null=True)
    servings = models.IntegerField(blank=True, null=True)
    site = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title

recipes/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from .models import Recipe, Category


class RecipeForm(forms.ModelForm):

    # custom form fields
    ingredients = forms.CharField(widget=CKEditorWidget(config_name='ingredients'), required=False)
    new_category = forms.CharField(required=False, label="New Category", widget=forms.TextInput(
        attrs={'placeholder': 'title'}))
    cat_image = forms.URLField(required=False, label="Image", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    cat_description = forms.CharField(required=False, label="Description", widget=forms.Textarea(
        attrs={'rows': '4', 'cols': '12', 'placeholder': 'Short description of category'}))
    category = forms.ModelChoiceField(required=False, queryset=Category.objects.all())

    # ModelForm fields               
    class Meta:
        model = Recipe
        fields = ['title', 'body', 'servings']
        widgets = {
            'body': CKEditorWidget(),
        }

    # relating available categories in drop-down to specific user
    def __init__(self, *args, user=None ,**kwargs):
        super().__init__(*args, **kwargs)
        if user:
            category = self.fields['category']
            category.queryset = Category.objects.filter(user__pk=user.pk)    

    # custom form validation
    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')
        title = cleaned_data.get('title')
        if not category and not new_category:
            raise forms.ValidationError(
                "No category given")
        if not title:
            raise forms.ValidationError(
                "No title given")


class ScraperForm(forms.Form):

    # custom form fields
    url = forms.URLField(label="Recipe URL", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    new_category = forms.CharField(required=False, label="New Category", widget=forms.TextInput(
        attrs={'placeholder': 'title'}))
    cat_image = forms.URLField(required=False, label="Image", widget=forms.TextInput(
        attrs={'placeholder': 'paste link here'}))
    cat_description = forms.CharField(required=False, label="Description", widget=forms.Textarea(
        attrs={'rows': '4', 'cols': '12', 'placeholder': 'Short description of new category'}))        
    category = forms.ModelChoiceField(required=False, queryset=Category.objects.all())

    # relating available categories in drop-down to specific user
    def __init__(self, *args, user=None ,**kwargs):
        super().__init__(*args, **kwargs)
        if user:
            category = self.fields['category']
            category.queryset = Category.objects.filter(user__pk=user.pk)

    # custom form validation
    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')
        if not category and not new_category:
            raise forms.ValidationError(
                "No category")        

recipes/views.py
import os

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate

from recipe_scrapers import scrape_me

from .forms import RecipeForm, ScraperForm
from .models import Recipe, Category
from .utils import *


# homepage
# all recipes and categories belonging to the user are queried and 
# sent to the front end to be rendered
def index(request):
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)
    django_settings = os.environ.get('DJANGO_SETTINGS_MODULE')
    if django_settings == 'alisite.settings.development':
        development = True
    else:
        development = False
            
    # some cleanup to find empty categories and delete them
    if categories:
        for cat in categories:
            empty_cat = True
            for rec in recipes:
                if rec.category.pk == cat.pk:
                    empty_cat = False
            if empty_cat:
                cat_del = Category.objects.get(pk=cat.pk)
                cat_del.delete()

            # update list of categories to reflect deleted ones    
            categories = Category.objects.filter(user__pk=user_pk)    

    return render(request, 'recipes/index.html', {
        'categories': categories,
        'recipes': recipes,
        'development': development
    })

# creating new recipe
def create(request):
    user_pk = request.user.pk  
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)   

    # handle for RecipeForm submission        
    if request.method == 'POST':      
        form = RecipeForm(request.POST)           
        if form.is_valid():

            # check if new category was given
            new_category = request.POST.get('new_category')            
            if new_category:
                # check if new category alredy exists
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')

                    data = collect_data(request)
                    rec_form = RecipeForm(user=request.user, initial=data)

                    return render(request, 'recipes/create.html', {
                        'rec_form': rec_form,
                        'categories': categories,
                        'recipes': recipes,
                    })

                # create recipe with new category       
                recipe = create_recipe_new_cat(user_pk, request)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            
            # create recipe with existing category
            elif request.POST.get('category'):
                recipe = create_recipe_existing_cat(user_pk, request)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))    

        # error message for incomplete recipe
        else:
            messages.info(request, 'Note: You must provide a title, category and body to save the recipe')         
                
            data = collect_data(request)               
            rec_form = RecipeForm(user=request.user, initial=data)

            return render(request, 'recipes/create.html', {
            'rec_form': rec_form,
            'categories': categories,
            'recipes': recipes,
        })


    rec_form = RecipeForm(user=request.user, initial={'servings': 1}) 
    
    return render(request, 'recipes/create.html', {
        'rec_form': rec_form,
        'categories': categories,
        'recipes': recipes,
    })

# editing a recipe
def edit_recipe(request, rec_pk):
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)

    # handle for RecipeForm submission
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():   
            recipe = Recipe.objects.get(pk=rec_pk)

            # check if new category was given
            new_category = request.POST.get('new_category')            
            if new_category:

                # check if new category alredy exists
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')

                    data = {'category': request.POST.get('category'),
                    'title': request.POST.get('title'),
                    'body': request.POST.get('body'),
                    'servings': request.POST.get('servings'),
                    'ingredients': request.POST.get('ingredients') }
                    rec_form = RecipeForm(user=request.user, initial=data)

                    return render(request, 'recipes/edit.html', {
                        'rec_form': rec_form,
                        'categories': categories,
                        'recipes': recipes,
                        'recipe': recipe
                    })

                # edit recipe with new category       
                recipe = edit_recipe_new_cat(request, recipe)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            
            # edit recipe with existing category
            elif request.POST.get('category'):
                recipe = edit_recipe_existing_cat(request, recipe)
                recipe.save()

                return redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))    

        # error message for incomplete form
        else:
            messages.info(request, 'Note: You must give a title, category and body to save the recipe') 

            data = collect_data(request)
            rec_form = RecipeForm(user=request.user, initial=data)

            return render(request, 'recipes/edit.html', {
            'rec_form': rec_form,
            'recipe': recipe,
            'categories': categories,
            'recipes': recipes,
        })   

    # retrieve recipe to be edited
    recipe = Recipe.objects.get(pk=rec_pk)

    # gather data to populate form to be edited   
    data = {'title': recipe.title,
            'category': recipe.category,
            'servings': recipe.servings,
            'body': recipe.body,
            'ingredients': recipe.ingredients} 
    rec_form = RecipeForm(initial=data, user=request.user)        
            
    return render(request, 'recipes/edit.html', {
        'categories': categories,
        'recipes': recipes,
        'rec_form': rec_form,
        'recipe': recipe,
    })

# lets scrape some recipes!
def get_recipe(request):

    # set up forms etc.
    form = ScraperForm(user=request.user)
    user_pk = request.user.pk
    recipes = Recipe.objects.filter(user__pk=user_pk)
    categories = Category.objects.filter(user__pk=user_pk)

    # handle for form submission
    if request.method == 'POST':
        form = ScraperForm(request.POST)
        if form.is_valid():
            try:                                                       
                
                # check if new category alredy exists
                new_category = request.POST.get('new_category')
                category_names = [cat.name for cat in categories]
                if new_category in category_names:
                    messages.info(request, 'Category Already Exists')
                    return redirect(reverse('recipes:get_recipe', kwargs={'user_pk': user_pk}))
                
                # handle for new category
                if new_category:                
                    recipe_url = request.POST.get('url')
                    online_recipe = scrape_me(recipe_url, wild_mode = True)                     
                    recipe = scrape_recipe_new_cat(user_pk, request, online_recipe)
                    recipe.save()                   
                    return  redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))

                # handle for existing category 
                else:                    
                    recipe_url = request.POST.get('url')
                    online_recipe = scrape_me(recipe_url, wild_mode = True)                      
                    recipe = scrape_recipe(user_pk, request, online_recipe)   
                    recipe.save()                    
                    return  redirect(reverse('recipes:view_recipe', kwargs={'rec_pk': recipe.pk}))
            except:
                messages.error(request, 'Oops, something went wrong. Please check that you have given a category. It is also possible that this recipe simply cannot be scraped :(')               
                data = {'url': request.POST.get('url'),
                        'category': request.POST.get('category'),
                        'new_category': request.POST.get('new_category'),
                        'cat_image': request.POST.get('cat_image'),
                        'cat_description': request.POST.get('cat_description')}                
                form = ScraperForm(initial=data, user=request.user)
                                
                return render(request, 'recipes/get_recipe.html', {
                    'form': form,
                    'recipes': recipes,
                    'categories': categories
                })                        
        else:
            messages.error(request, 'Please provide a category')           
            data = {'url': request.POST.get('url'),

recipes/templates/recipes/includes/messages.html
{% if messages %} 
  {% for message in messages %}
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    {{message}} 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %} 
{% endif %}

recipes/templates/recipes/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'recipes:index' %}" style="font-family: AlwaysForever; font-size: 35px; margin-bottom: -15px; font-weight: bold">Ali's Kitchen</a>
        <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <form action="{% url 'recipes:search' %}" class="d-flex" role="search"  method="POST">
              {%csrf_token%}
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="user_search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>   
            <ul class="navbar-nav">                
              {% for cat in categories %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{cat|title}}
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    {% for rec in recipes|dictsort:"title" %} 
                      {% if rec.category == cat %}
                        <li>
                          <a class="dropdown-item" href="{% url 'recipes:view_recipe' rec_pk=rec.pk %}">
                            {{rec}}
                          </a>
                        </li>
                      {% endif %} 
                    {% endfor %}
                  </ul>   
                </li>
              {% endfor %}          
              <li>
                <a style="color: whitesmoke;" class="nav-link" href="{% url 'recipes:create' %}">New</a>
              </li>
              <li>
                <a style="color: whitesmoke;" class="nav-link" href="{% url 'recipes:get_recipe' %}">From The Internet</a>
              </li>
            </ul>         
        </div>
        <div style="margin-right: 25px;">
          <a href="{% url 'recipes:logout' %}" style="color:whitesmoke"><small>Logout</small></a>
        </div> 
      {% endif %}
           
    </div>
</nav>

recipes/templates/recipes/includes/recipe_form.html
{% csrf_token %}
<div class="center">
    <div style="border: 1px solid #a9aaaa; border-radius:  15px; padding: 33px; background-color: #383e3e">
        <div class="cat-flex">
        <!--csrf_token and ingredient form-->
            {{rec_form.ingredient.label}} 
            {{rec_form.ingredient}}
        </div>
        <div class="button-flex">
        <!--form buttons-->
            <button id="button" formaction="/ingredient_handler/add,{{recipe.pk}}">Ingredient</button>
            <button id="button" formaction="/ingredient_handler/header,{{recipe.pk}}">Header</button>
            <button id="button" formaction="/ingredient_handler/del,{{recipe.pk}}">Delete</button>
        </div>        
        <div class="row-container">
            <div class="ingredient-list">
            <!--list ingredients-->
            <!--if '!' is appended to start, the ingredient is a heading and is printed in bold-->
            <!--the '!' gets sliced off the end-->
                {% if ingr_list %}
                    <ul>
                    {% for i in ingr_list %}
                        {% if i.0 == '!' %}
                            <br>
                            <strong>{{i| slice:'1:'}}</strong>
                        {% else %}
                            <li>{{i}}</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                {% endif %}        

            </div>
        </div>
    </div>
</div>

<div class="seperate" style="padding: 25px; display: flex; flex-wrap: wrap;" >
    <div >
        <div class="column-container" >
            <div class="cat-flex">
                {{rec_form.category.label}}
                {{rec_form.category}}
            </div>
            <div class="cat-flex">                
                {{rec_form.title.label}}
                {{rec_form.title}}
            </div>
            <div class="cat-flex" style="width: 75px">               
                {{rec_form.servings.label}}
                {{rec_form.servings}}
            </div>
            <br><br>
        </div>
    </div>
    <div style="width: 50%">
        <div style="border: 1px solid #a9aaaa; border-radius:  15px; background-color: #383e3e; width: 460px; margin-left: -30px; padding: 10px;">
            <div class="row-container">
                <div class="cat-flex" >
                    {{rec_form.new_category.label}}
                    {{rec_form.new_category.errors}}{{rec_form.new_category}}
                </div>
                <div class="cat-flex" >
                    {{rec_form.cat_image.label}}
                    {{rec_form.cat_image}}
                    <p style="color:#ccc"><small>(optional)</small></p>
                </div>
            </div>
            <p style="margin-top: -25px">
            <div class="cat-flex" style=" width: 375px;">
                {{rec_form.cat_description.label}}
                {{rec_form.cat_description}}
                <p style="color:#ccc"><small>(optional)</small></p>
            </div>
            </p>
        </div>
    </div>    
</div>
<br><br>            
<div class="center">
    <div class="column-container">
        {{rec_form.media}}
        {{rec_form.body}}
        <br><br>
        {% if recipe.pk %}
            <div class="row-container">
                <input id="button" type="submit" value="Save">
                <button id="button" formaction="{% url 'recipes:delete_recipe' rec_pk=recipe.pk %}">Delete</button>
            </div>
        {% else %}    
            <input id="button" type="submit" value="create">
        {% endif %}    
    </div>    
</div>
<br>

recipes/templates/recipes/includes/recipe_form_create.html
<div class="container">
    <div class="row">
        <div class="col">
            <div class="center">
                <div style="width: 263px; padding: 5px;"> 
                    <div class="cat-flex" style="width: 250px" >                      
                        {{rec_form.title.label}}
                        {{rec_form.title}}
                    </div>                   
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.category.label}}
                        {{rec_form.errors}}{{rec_form.category}}
                    </div>         
                    <div class="cat-flex" style=" width: 75px;">
                        {{rec_form.servings.label}}
                        {{rec_form.servings}}
                    </div>
                    <br><br>
                </div>
            </div>
        </div> 
        <div class="col">
            <div class="center">
                <div style="border: 1px solid #a9aaaa; border-radius:  15px; background-color: #383e3e; width: 263px; padding: 5px;">                
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.new_category.label}}
                        {{rec_form.new_category.errors}}
                        {{rec_form.new_category}}
                    </div>
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.cat_image.label}}
                        {{rec_form.cat_image}}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>             
                    <div class="cat-flex" style=" width: 250px;">
                        {{rec_form.cat_description.label}}
                        {{rec_form.cat_description}}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                </div>
            </div>
        </div>       
    </div>
    <br><br>
    <hr>
    <br><br>      

    <div class="center">
        <div style="border: 1px solid #a9aaaa; border-radius:  15px; padding: 20px; background-color: #383e3e">
            <div class="cat-flex">
                {{rec_form.ingredients.label}}
                <br><br> 
                {{rec_form.ingredients}}
            </div>
        </div>
    </div>
    <br><br>
    <hr>
    <br><br>
    <div class="center">
        <div class="column-container">
            {{rec_form.media}}
            {{rec_form.body| safe}}
            <br><br>
            <input id="button" type="submit" value="create">  
        </div>    
    </div>
    <br>
</div>

recipes/templates/recipes/includes/recipe_form_edit.html
<div class="container">
    <div class="row">
        <div class="col">
            <div class="center">
                <div style="width: 263px; padding: 5px;"> 
                    <div class="cat-flex" style="width: 250px" >   
                        {{rec_form.title.label}}
                        {{rec_form.title}}
                    </div>                   
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.category.label}}
                        {{rec_form.errors}}{{rec_form.category}}
                    </div>         
                    <div class="cat-flex" style=" width: 75px;">
                        {{rec_form.servings.label}}
                        {{rec_form.servings}}
                    </div>
                    <br><br>
                </div>
            </div>
        </div> 
        <div class="col">
            <div class="center">
                <div style="border: 1px solid #a9aaaa; border-radius:  15px; background-color: #383e3e; width: 263px; padding: 5px;">                
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.new_category.label}}
                        {{rec_form.new_category.errors}}
                        {{rec_form.new_category}}
                    </div>
                    <div class="cat-flex" style="width: 250px" >
                        {{rec_form.cat_image.label}}
                        {{rec_form.cat_image}}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>             
                    <div class="cat-flex" style=" width: 250px;">
                        {{rec_form.cat_description.label}}
                        {{rec_form.cat_description}}
                        <p style="color:#ccc"><small>(optional)</small></p>
                    </div>
                </div>
            </div>
        </div>       
    </div>
    <br><br>
    <hr>
    <br><br>      

    <div class="center">
        <div style="border: 1px solid #a9aaaa; border-radius:  15px; padding: 20px; background-color: #383e3e">
            <div class="cat-flex">
                {{rec_form.ingredients.label}}
                <br><br> 
                {{rec_form.ingredients}}
            </div>
        </div>
    </div>
    <br><br>
    <hr>
    <br><br>           
    <div class="center">
        <div class="column-container">
            {{rec_form.media}}
            {{rec_form.body| safe}}
            <br><br>
            <div class="row-container">
                <input id="button" type="submit" value="Save">
                <button id="button" formaction="{% url 'recipes:delete_recipe' rec_pk=recipe.pk %}">Delete</button>
            </div>  
        </div>    
    </div>
    <br>
</div>